---
build:
  dir: build
  imports:
  - github.com/austin362667/shadow
  targets:
  - name: shadow-amd64-linux
    os: linux
    arch: amd64
  - name: shadow-arm64-darwin
    os: darwin
    arch: arm64

---
sessions:
  binance:
    exchange: binance
    envVarPrefix: BINANCE
    #max:
  #  exchange: max
  #  envVarPrefix: MAX

backtest:
  startTime: "2021-11-01"
  endTime: "2021-11-20"
  symbols:
  - BTCUSDT
  account:
    makerCommission: 15
    takerCommission: 15
    balances:
      BTC: 0.0
      USDT: 500.0

exchangeStrategies:
- on: binance
  shadow:
    symbol: "BTCUSDT"
    interval: 4h

